name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: basic-docker-template

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Get repository owner
      run: echo "REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    # Not a push to master - just test the build
    - name: Build ${{ env.CONTAINER_NAME }}
      if: github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: "ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.CONTAINER_NAME }}:latest"

    # Delete this build step in order to publish your build
    - name: Template pull tab - remove this build step!
      run: echo "Delete this build step in order to publish your build" & exit 1

    - name: Bump version
      if: github.ref == 'refs/heads/master'
      id: bump_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare version string
      if: github.ref == 'refs/heads/master'
      run: echo "VERSION_NUMBER=$(echo ${{ steps.bump_version.outputs.new_tag }} | sed 's/[v]//g')" >> $GITHUB_ENV

    - name: Login to ghcr.io
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Push to master - build and push to ghcr
    - name: Build and push ${{ env.CONTAINER_NAME }}
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: "ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.CONTAINER_NAME }}:latest,ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.CONTAINER_NAME }}:${{ env.VERSION_NUMBER }}"

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }}
        body: ${{ steps.bump_version.outputs.changelog }}
